# Generated by Django 3.0.6 on 2020-08-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
